### ISSUE TITLE
simple-todos-react not working in windows environment

### ISSUE THREAD

**Issue by AnnotatedJS** [meteor/simple-todos-react#5]
I downloaded the zip file and tried to run it on my pc. It gave an error.
And a suggestion to update it.
The update gave also an error.

I tried to attach file with log but that was not allowed.
# Therefore a copy and paste of the log below.

Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\René>d:

D:>cd simple-todos-react-master

D:\simple-todos-react-master>meteor
[[[[[ ~\D\simple-todos-react-master ]]]]]

=> Started proxy.
=> Meteor 1.2.1 is available. Update this project with 'meteor update'.

C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: Could not find isopack data with format isopack-1.
This isopack was likely built with a much newer version of Meteor.
    at Function.readMetadataFromDirectory (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\isopack.js:323:13)
    at [object Object]._.extend._alreadyDownloaded (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:319:35)
    at [object Object]._.extend._makeDownloader (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:383:33)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:524:29
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:521:20
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\package-map.js:50:7
    at Function._.each._.forEach (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at [object Object]._.extend.eachPackage (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\package-map.js:42:7)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\tropohouse.js:518:16)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:668:25
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:667:20
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\catalog.js:100:5
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:666:13)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:238:35
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:228:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:216:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\project-context.js:221:10)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:520:29
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at bundleApp (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:519:31)
    at [object Object]._.extend._runOnce (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:591:35)
    at [object Object]._.extend._fiber (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:821:28)
    at C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\tools\run-app.js:402:12

D:\simple-todos-react-master>meteor update

C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
TypeError: Cannot call method 'replace' of null
    at convert (C:\tools\utils\colon-converter.js:49:15)
    at convertBySchema (C:\tools\utils\colon-converter.js:18:12)
    at C:\tools\utils\colon-converter.js:42:18
    at Function._.each._.forEach (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at convertBySchema (C:\tools\utils\colon-converter.js:40:5)
    at C:\tools\utils\colon-converter.js:32:14
    at Array.map (native)
    at Function._.map._.collect (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:97:56)
    at convertBySchema (C:\tools\utils\colon-converter.js:31:14)
    at C:\tools\utils\colon-converter.js:42:18
    at Function._.each._.forEach (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at convertBySchema (C:\tools\utils\colon-converter.js:40:5)
    at Object.exports.convertJSImage (C:\tools\utils\colon-converter.js:88:10)
    at C:\tools\packaging\tropohouse.js:131:46
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at Object.exports._extractAndConvert (C:\tools\packaging\tropohouse.js:122:9)
    at [object Object]._.extend._downloadBuildToTempDir (C:\tools\packaging\tropohouse.js:308:20)
    at C:\tools\packaging\tropohouse.js:483:39
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at C:\tools\packaging\tropohouse.js:479:24
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Ren├®\AppData\Local.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:478:11
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at Object.download (C:\tools\packaging\tropohouse.js:437:20)
    at C:\tools\packaging\tropohouse.js:575:22
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:572:20)
    at C:\tools\project-context.js:702:25
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at C:\tools\project-context.js:701:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages (C:\tools\project-context.js:700:13)
    at C:\tools\project-context.js:257:35
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.js:247:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\tools\project-context.js:235:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.js:240:10)
    at C:\tools\cli\commands-packages.js:1506:20
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at Object.main.captureAndExit (C:\tools\cli\main.js:270:29)
    at maybeUpdateRelease (C:\tools\cli\commands-packages.js:1505:8)
    at Command.main.registerCommand.name [as func](C:toolsclicommands-packages.js:1577:29)
    at C:\tools\cli\main.js:1378:23

D:\simple-todos-react-master>

D:\simple-todos-react-master>

**Comment by herpdederp** [comment]
Same here tried "meteor update" got more errors

**Comment by mdtamjeed** [comment]
Is this resolved? I am experiencing the same setback.

**Comment by mdtamjeed** [comment]
meteor remove react
and then
meteor add react
Solves the issue. Strange, but it worked!

**Comment by stubailo** [comment]
Ah this must be because the example app is outdated. We should improve that. You might also have been able to fix it via `meteor update`.

**Comment by mdtamjeed** [comment]
as commented by @herpdederp , it did get worse

**Comment by pechitook** [comment]
This error just happened to me, both on this repo and on sample-todos-angular, under OSX. Effectively, `meteor remove angular && meteor add angular && meteor update` solved the error I was getting, which was `angular is not defined`. 

Simply cloning and running `meteor` is not working, maybe running a meteor update on the repo and committing the new versions can fix this.

**Comment by hwillson** [comment]
A new version of the tutorial will be published shortly. Please try things out and post back if you're still encountering this problem. Thanks!
